#!/usr/bin/env python3
"""Generate deterministic FPGA station maps and all-pairs distance ROM data."""

from __future__ import annotations

import csv
import heapq
import json
from dataclasses import dataclass
from decimal import Decimal
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
INPUT = ROOT / "data" / "metro_lines.txt"
DATA_DIR = ROOT / "data"
SRC_DIR = ROOT / "src"


@dataclass(frozen=True)
class MetroLine:
    line_id: int
    name: str
    stations: list[str]
    distances_m: list[int]


def read_lines(path: Path) -> list[MetroLine]:
    tokens = path.read_text(encoding="utf-8").split()
    cursor = 0
    line_total = int(tokens[cursor])
    cursor += 1
    lines: list[MetroLine] = []

    for line_id in range(1, line_total + 1):
        name = tokens[cursor]
        count = int(tokens[cursor + 1])
        cursor += 2
        stations = tokens[cursor : cursor + count]
        cursor += count
        distances = [
            int(Decimal(value) * 1000)
            for value in tokens[cursor : cursor + count - 1]
        ]
        cursor += count - 1
        if len(stations) != count or len(distances) != count - 1:
            raise ValueError(f"Invalid station data for {name}")
        lines.append(MetroLine(line_id, name, stations, distances))

    if cursor != len(tokens):
        raise ValueError(f"Unexpected trailing tokens: {tokens[cursor:]}")
    return lines


def build_graph(lines: list[MetroLine]):
    station_to_id: dict[str, int] = {}
    id_to_station: list[str] = []

    for line in lines:
        for station in line.stations:
            if station not in station_to_id:
                station_to_id[station] = len(id_to_station)
                id_to_station.append(station)

    graph: list[list[tuple[int, int]]] = [[] for _ in id_to_station]
    for line in lines:
        for index, distance_m in enumerate(line.distances_m):
            u = station_to_id[line.stations[index]]
            v = station_to_id[line.stations[index + 1]]
            graph[u].append((v, distance_m))
            graph[v].append((u, distance_m))

    return station_to_id, id_to_station, graph


def dijkstra(graph: list[list[tuple[int, int]]], start: int) -> list[int]:
    infinity = 10**12
    distance = [infinity] * len(graph)
    distance[start] = 0
    queue = [(0, start)]

    while queue:
        current_distance, u = heapq.heappop(queue)
        if current_distance != distance[u]:
            continue
        for v, weight in graph[u]:
            candidate = current_distance + weight
            if candidate < distance[v]:
                distance[v] = candidate
                heapq.heappush(queue, (candidate, v))

    if any(value == infinity for value in distance):
        raise ValueError("The selected metro graph is disconnected")
    return distance


def fare_from_distance(distance_m: int) -> int:
    if distance_m <= 4000:
        return 2
    if distance_m <= 9000:
        return 3
    if distance_m <= 14000:
        return 4
    if distance_m <= 21000:
        return 5
    if distance_m <= 28000:
        return 6
    if distance_m <= 37000:
        return 7
    if distance_m <= 48000:
        return 8
    if distance_m <= 61000:
        return 9
    return 9 + (distance_m - 61000 + 14999) // 15000


def write_station_csv(lines, station_to_id) -> None:
    output = DATA_DIR / "station_codes.csv"
    with output.open("w", encoding="utf-8-sig", newline="") as handle:
        writer = csv.writer(handle)
        writer.writerow(
            [
                "line_id",
                "line_name",
                "local_index",
                "display_code",
                "global_id",
                "station_name",
                "distance_to_next_m",
            ]
        )
        for line in lines:
            for local_index, station in enumerate(line.stations, start=1):
                next_distance = (
                    line.distances_m[local_index - 1]
                    if local_index <= len(line.distances_m)
                    else ""
                )
                writer.writerow(
                    [
                        line.line_id,
                        line.name,
                        local_index,
                        line.line_id * 100 + local_index,
                        station_to_id[station],
                        station,
                        next_distance,
                    ]
                )


def write_station_mapper(lines, station_to_id) -> None:
    output = SRC_DIR / "station_mapper.v"
    text = [
        "`timescale 1ns / 1ps",
        "",
        "// Generated by scripts/generate_metro_data.py. Do not edit manually.",
        "module station_mapper (",
        "    input  wire [2:0] line_id,",
        "    input  wire [5:0] local_index,",
        "    output reg  [6:0] global_id,",
        "    output reg        valid,",
        "    output reg  [5:0] station_count",
        ");",
        "",
        "    always @(*) begin",
        "        global_id = 7'd0;",
        "        valid = 1'b0;",
        "        station_count = 6'd0;",
        "        case (line_id)",
    ]
    for line in lines:
        text.extend(
            [
                f"            3'd{line.line_id}: begin",
                f"                station_count = 6'd{len(line.stations)};",
                "                case (local_index)",
            ]
        )
        for local_index, station in enumerate(line.stations, start=1):
            global_id = station_to_id[station]
            text.append(
                f"                    6'd{local_index}: begin global_id = 7'd{global_id}; valid = 1'b1; end"
            )
        text.extend(
            [
                "                    default: begin global_id = 7'd0; valid = 1'b0; end",
                "                endcase",
                "            end",
            ]
        )
    text.extend(
        [
            "            default: begin",
            "                station_count = 6'd0;",
            "                global_id = 7'd0;",
            "                valid = 1'b0;",
            "            end",
            "        endcase",
            "    end",
            "endmodule",
            "",
        ]
    )
    output.write_text("\n".join(text), encoding="ascii")


def write_triangle_base(station_count: int) -> None:
    output = SRC_DIR / "triangle_base_rom.v"
    text = [
        "`timescale 1ns / 1ps",
        "",
        "// Generated triangular-matrix base address table.",
        "module triangle_base_rom (",
        "    input  wire [6:0] index,",
        "    output reg  [12:0] base",
        ");",
        "    always @(*) begin",
        "        case (index)",
    ]
    for index in range(station_count):
        text.append(
            f"            7'd{index}: base = 13'd{index * (index - 1) // 2};"
        )
    text.extend(
        [
            "            default: base = 13'd0;",
            "        endcase",
            "    end",
            "endmodule",
            "",
        ]
    )
    output.write_text("\n".join(text), encoding="ascii")


def write_distance_rom(all_pairs: list[list[int]]) -> None:
    output = DATA_DIR / "distance_rom.mem"
    with output.open("w", encoding="ascii", newline="\n") as handle:
        for high in range(1, len(all_pairs)):
            for low in range(high):
                distance = all_pairs[high][low]
                if not 0 <= distance < (1 << 17):
                    raise ValueError(f"Distance {distance} does not fit in 17 bits")
                handle.write(f"{distance:05x}\n")


def main() -> None:
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    SRC_DIR.mkdir(parents=True, exist_ok=True)
    lines = read_lines(INPUT)
    station_to_id, id_to_station, graph = build_graph(lines)
    all_pairs = [dijkstra(graph, station) for station in range(len(graph))]

    write_station_csv(lines, station_to_id)
    write_station_mapper(lines, station_to_id)
    write_triangle_base(len(id_to_station))
    write_distance_rom(all_pairs)

    pair_count = len(id_to_station) * (len(id_to_station) - 1) // 2
    maximum_distance = max(max(row) for row in all_pairs)
    metadata = {
        "line_count": len(lines),
        "line_station_counts": [len(line.stations) for line in lines],
        "station_occurrences": sum(len(line.stations) for line in lines),
        "unique_station_count": len(id_to_station),
        "pair_count": pair_count,
        "distance_width_bits": 17,
        "maximum_distance_m": maximum_distance,
        "maximum_fare_yuan": fare_from_distance(maximum_distance),
    }
    (DATA_DIR / "metadata.json").write_text(
        json.dumps(metadata, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )

    if not id_to_station or pair_count != len(id_to_station) * (len(id_to_station) - 1) // 2:
        raise AssertionError("generated station or pair count is inconsistent")
    print(json.dumps(metadata, ensure_ascii=False))


if __name__ == "__main__":
    main()
