`timescale 1ns / 1ps

// Generated by scripts/generate_metro_data.py. Do not edit manually.
module station_mapper (
    input  wire [2:0] line_id,
    input  wire [5:0] local_index,
    output reg  [6:0] global_id,
    output reg        valid,
    output reg  [5:0] station_count
);

    always @(*) begin
        global_id = 7'd0;
        valid = 1'b0;
        station_count = 6'd0;
        case (line_id)
            3'd1: begin
                station_count = 6'd32;
                case (local_index)
                    6'd1: begin global_id = 7'd0; valid = 1'b1; end
                    6'd2: begin global_id = 7'd1; valid = 1'b1; end
                    6'd3: begin global_id = 7'd2; valid = 1'b1; end
                    6'd4: begin global_id = 7'd3; valid = 1'b1; end
                    6'd5: begin global_id = 7'd4; valid = 1'b1; end
                    6'd6: begin global_id = 7'd5; valid = 1'b1; end
                    6'd7: begin global_id = 7'd6; valid = 1'b1; end
                    6'd8: begin global_id = 7'd7; valid = 1'b1; end
                    6'd9: begin global_id = 7'd8; valid = 1'b1; end
                    6'd10: begin global_id = 7'd9; valid = 1'b1; end
                    6'd11: begin global_id = 7'd10; valid = 1'b1; end
                    6'd12: begin global_id = 7'd11; valid = 1'b1; end
                    6'd13: begin global_id = 7'd12; valid = 1'b1; end
                    6'd14: begin global_id = 7'd13; valid = 1'b1; end
                    6'd15: begin global_id = 7'd14; valid = 1'b1; end
                    6'd16: begin global_id = 7'd15; valid = 1'b1; end
                    6'd17: begin global_id = 7'd16; valid = 1'b1; end
                    6'd18: begin global_id = 7'd17; valid = 1'b1; end
                    6'd19: begin global_id = 7'd18; valid = 1'b1; end
                    6'd20: begin global_id = 7'd19; valid = 1'b1; end
                    6'd21: begin global_id = 7'd20; valid = 1'b1; end
                    6'd22: begin global_id = 7'd21; valid = 1'b1; end
                    6'd23: begin global_id = 7'd22; valid = 1'b1; end
                    6'd24: begin global_id = 7'd23; valid = 1'b1; end
                    6'd25: begin global_id = 7'd24; valid = 1'b1; end
                    6'd26: begin global_id = 7'd25; valid = 1'b1; end
                    6'd27: begin global_id = 7'd26; valid = 1'b1; end
                    6'd28: begin global_id = 7'd27; valid = 1'b1; end
                    6'd29: begin global_id = 7'd28; valid = 1'b1; end
                    6'd30: begin global_id = 7'd29; valid = 1'b1; end
                    6'd31: begin global_id = 7'd30; valid = 1'b1; end
                    6'd32: begin global_id = 7'd31; valid = 1'b1; end
                    default: begin global_id = 7'd0; valid = 1'b0; end
                endcase
            end
            3'd2: begin
                station_count = 6'd30;
                case (local_index)
                    6'd1: begin global_id = 7'd32; valid = 1'b1; end
                    6'd2: begin global_id = 7'd33; valid = 1'b1; end
                    6'd3: begin global_id = 7'd34; valid = 1'b1; end
                    6'd4: begin global_id = 7'd35; valid = 1'b1; end
                    6'd5: begin global_id = 7'd36; valid = 1'b1; end
                    6'd6: begin global_id = 7'd37; valid = 1'b1; end
                    6'd7: begin global_id = 7'd38; valid = 1'b1; end
                    6'd8: begin global_id = 7'd39; valid = 1'b1; end
                    6'd9: begin global_id = 7'd40; valid = 1'b1; end
                    6'd10: begin global_id = 7'd41; valid = 1'b1; end
                    6'd11: begin global_id = 7'd42; valid = 1'b1; end
                    6'd12: begin global_id = 7'd43; valid = 1'b1; end
                    6'd13: begin global_id = 7'd44; valid = 1'b1; end
                    6'd14: begin global_id = 7'd45; valid = 1'b1; end
                    6'd15: begin global_id = 7'd12; valid = 1'b1; end
                    6'd16: begin global_id = 7'd46; valid = 1'b1; end
                    6'd17: begin global_id = 7'd47; valid = 1'b1; end
                    6'd18: begin global_id = 7'd48; valid = 1'b1; end
                    6'd19: begin global_id = 7'd49; valid = 1'b1; end
                    6'd20: begin global_id = 7'd50; valid = 1'b1; end
                    6'd21: begin global_id = 7'd51; valid = 1'b1; end
                    6'd22: begin global_id = 7'd52; valid = 1'b1; end
                    6'd23: begin global_id = 7'd53; valid = 1'b1; end
                    6'd24: begin global_id = 7'd54; valid = 1'b1; end
                    6'd25: begin global_id = 7'd55; valid = 1'b1; end
                    6'd26: begin global_id = 7'd56; valid = 1'b1; end
                    6'd27: begin global_id = 7'd57; valid = 1'b1; end
                    6'd28: begin global_id = 7'd58; valid = 1'b1; end
                    6'd29: begin global_id = 7'd59; valid = 1'b1; end
                    6'd30: begin global_id = 7'd60; valid = 1'b1; end
                    default: begin global_id = 7'd0; valid = 1'b0; end
                endcase
            end
            3'd3: begin
                station_count = 6'd29;
                case (local_index)
                    6'd1: begin global_id = 7'd61; valid = 1'b1; end
                    6'd2: begin global_id = 7'd62; valid = 1'b1; end
                    6'd3: begin global_id = 7'd63; valid = 1'b1; end
                    6'd4: begin global_id = 7'd64; valid = 1'b1; end
                    6'd5: begin global_id = 7'd65; valid = 1'b1; end
                    6'd6: begin global_id = 7'd66; valid = 1'b1; end
                    6'd7: begin global_id = 7'd67; valid = 1'b1; end
                    6'd8: begin global_id = 7'd68; valid = 1'b1; end
                    6'd9: begin global_id = 7'd69; valid = 1'b1; end
                    6'd10: begin global_id = 7'd7; valid = 1'b1; end
                    6'd11: begin global_id = 7'd70; valid = 1'b1; end
                    6'd12: begin global_id = 7'd71; valid = 1'b1; end
                    6'd13: begin global_id = 7'd72; valid = 1'b1; end
                    6'd14: begin global_id = 7'd46; valid = 1'b1; end
                    6'd15: begin global_id = 7'd73; valid = 1'b1; end
                    6'd16: begin global_id = 7'd74; valid = 1'b1; end
                    6'd17: begin global_id = 7'd75; valid = 1'b1; end
                    6'd18: begin global_id = 7'd76; valid = 1'b1; end
                    6'd19: begin global_id = 7'd77; valid = 1'b1; end
                    6'd20: begin global_id = 7'd78; valid = 1'b1; end
                    6'd21: begin global_id = 7'd79; valid = 1'b1; end
                    6'd22: begin global_id = 7'd20; valid = 1'b1; end
                    6'd23: begin global_id = 7'd80; valid = 1'b1; end
                    6'd24: begin global_id = 7'd81; valid = 1'b1; end
                    6'd25: begin global_id = 7'd82; valid = 1'b1; end
                    6'd26: begin global_id = 7'd83; valid = 1'b1; end
                    6'd27: begin global_id = 7'd84; valid = 1'b1; end
                    6'd28: begin global_id = 7'd85; valid = 1'b1; end
                    6'd29: begin global_id = 7'd86; valid = 1'b1; end
                    default: begin global_id = 7'd0; valid = 1'b0; end
                endcase
            end
            3'd4: begin
                station_count = 6'd18;
                case (local_index)
                    6'd1: begin global_id = 7'd87; valid = 1'b1; end
                    6'd2: begin global_id = 7'd88; valid = 1'b1; end
                    6'd3: begin global_id = 7'd89; valid = 1'b1; end
                    6'd4: begin global_id = 7'd10; valid = 1'b1; end
                    6'd5: begin global_id = 7'd71; valid = 1'b1; end
                    6'd6: begin global_id = 7'd90; valid = 1'b1; end
                    6'd7: begin global_id = 7'd91; valid = 1'b1; end
                    6'd8: begin global_id = 7'd92; valid = 1'b1; end
                    6'd9: begin global_id = 7'd93; valid = 1'b1; end
                    6'd10: begin global_id = 7'd94; valid = 1'b1; end
                    6'd11: begin global_id = 7'd95; valid = 1'b1; end
                    6'd12: begin global_id = 7'd54; valid = 1'b1; end
                    6'd13: begin global_id = 7'd96; valid = 1'b1; end
                    6'd14: begin global_id = 7'd97; valid = 1'b1; end
                    6'd15: begin global_id = 7'd98; valid = 1'b1; end
                    6'd16: begin global_id = 7'd99; valid = 1'b1; end
                    6'd17: begin global_id = 7'd100; valid = 1'b1; end
                    6'd18: begin global_id = 7'd101; valid = 1'b1; end
                    default: begin global_id = 7'd0; valid = 1'b0; end
                endcase
            end
            default: begin
                station_count = 6'd0;
                global_id = 7'd0;
                valid = 1'b0;
            end
        endcase
    end
endmodule
